#!/bin/bash

# Check if the argument is 'install'
if [ "$1" == "install" ]; then
  echo "Installing.."
  npm install
  npm run build
  if [ $? -eq 0 ]; then
    echo "Instal succeeded"
    exit 0
  else
    echo "Install failed"
    exit 1
  fi
fi

if [ "$1" == "test" ]; then
  npm run test
  if [ $? -eq 0 ]; then
    exit 0
  else
    echo "Tests failed"
    exit 1
  fi
fi

node dist/index.js "$1"